---
- name: configure sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    backup: yes
    create: yes
    validate: 'sshd -t -f %s'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '^\#?Port\s+(.*)$'
      line: 'Port {{ sshd_port }}'
    - regexp: '^\#?PermitRootLogin\s+(.*)$'
      line: 'PermitRootLogin {{ sshd_permitrootlogin }}'
    - regexp: '^\#?PermitEmptyPasswords\s+(.*)$'
      line: 'PermitEmptyPasswords {{ sshd_permitemptypasswords }}'
    - regexp: '^\#?PasswordAuthentication\s+(.*)$'
      line: 'PasswordAuthentication {{ sshd_passwordauthentication }}'
    - regexp: '^\#?GSSAPIAuthentication\s+(.*)$'
      line: 'GSSAPIAuthentication {{ sshd_gssapiauthentication }}'
    - regexp: '^\#?PubkeyAuthentication\s+(.*)$'
      line: 'PubkeyAuthentication {{ sshd_pubkeyauthentication }}'
  notify: restart sshd
